### ISSUE TITLE
Suggestion: Clean up settings page (whitespace sanitization)

### ISSUE THREAD

**Issue by rvarbanov** [zaggino/brackets-git#1033]
Git does not need handle code whitespace sanitization, I suggest that we remove that functionality from Brackets Git.

Remove:

- Add endline at the end of file
- Normalize line endings (to \n)
- Clear whitespace on file save

A really good substitution: White Space Sanitizer by Miguel Castillo https://github.com/MiguelCastillo/Brackets-wsSanitizer

**Comment by zaggino** [comment]
Nope, there're two thing tied up to Git which makes Brackets Git whitespace cleanup better:
1) Whitespace is cleaned up only before commit, I hate it being cleaned up on every file save because it moves my cursor around.
2) Whitespace is cleaned up only for the lines, which are going to be committed and not from the whole file, which helps to make PRs clean.
