### ISSUE TITLE
Error when cloning remote repository

### ISSUE THREAD

**Issue by johnhidey** [zaggino/brackets-git#596]
When attempting to clone a repository from within Brackets I receive this error.  I can clone it git bash and all works fine, but not able to through brackets.

---

_Brackets 0.40.0-13109 (win), Git 1.9.2.msysgit.0 & Brackets-Git 0.13.20_

```
Error: cmd-spawn-timeout: git clone https://johnhidey@bitbucket.org/hideycom/hidey.com.git . --progress
```

```
call: git clone https://johnhidey@bitbucket.org/hideycom/hidey.com.git . --progress
Error: cmd-spawn-timeout: git clone https://johnhidey@bitbucket.org/hideycom/hidey.com.git . --progress
    at timeoutPromise (file:///C:/Users/jhidey/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:199:27)
    at file:///C:/Users/jhidey/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:242:33
```

**Comment by cilygalonmarketing** [comment]
Hi, this is my first time using git-hub and I'm just trying to upload my code (html/css) from brackets into a website so that it can be marked by university. watching a youtube tutorial to do so but I've encountered this problem 
![2019-05-01](https://user-images.githubusercontent.com/50174427/57023762-ce796800-6c2a-11e9-9877-e37c9a2ad5e0.png)
Anyone able to help?

**Comment by zaggino** [comment]
@cilygalonmarketing this project is not maintained anymore
