### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by CydGoblin** [zaggino/brackets-git#837]
:disappointed: After last update i'm getting this error when opening brackets:
![image](https://cloud.githubusercontent.com/assets/4932347/5348663/afa971b4-7eee-11e4-91cc-064c29b0c9aa.png)

If I Debug it i get this one:
![image](https://cloud.githubusercontent.com/assets/4932347/5348671/c57b4e04-7eee-11e4-8b1a-edb9c3c2521e.png)

Developer tools:
![image](https://cloud.githubusercontent.com/assets/4932347/5348687/fa038a92-7eee-11e4-8b0f-27882c37204c.png)

Update: Also, it won't let me uninstall it

**Comment by j0n4s** [comment]
Help me please, I have the below error I made an installation from 0 and is happening (sorry my English is bad)

![error brackets git](https://cloud.githubusercontent.com/assets/5799706/9073703/cae80846-3ac8-11e5-9a6d-f3d447bf9043.png)

**Comment by zaggino** [comment]
https://github.com/zaggino/brackets-git/issues/1109
https://github.com/zaggino/brackets-git/issues/410
https://github.com/zaggino/brackets-git/issues/468

**Comment by VinodIntl** [comment]
In my case, when I got the 'Failed to launch git executable..' error on my mac, I tried running the git from terminal command line. It displayed a message asking to accept new licensing agreement (due to a recent update of Xcode). Once I accepted the licensing terms, the Brackets Git plugin started working again. Hope this helps.
