### ISSUE TITLE
Pushing to remote failed When i use 2 steps verification

### ISSUE THREAD

**Issue by roberthchan** [zaggino/brackets-git#935]
I use Auth to create tokens and allow to use my account, but cant see the dialog to put my token. When i disabled works fine
Im using opensuse 13.2 KDE.
--------------------------------

*Brackets 1.1.0-15558 (linux), Git 2.1.4 & Brackets-Git 0.14.17*

**Pushing to remote failed**

```
Error: remote: Invalid username or password.
fatal: Authentication failed for 'https://roberthchan:***@github.com/roberthchan/wave-runner.git/'
```

```
call: git push --porcelain --progress Runner master
Error: remote: Invalid username or password.
fatal: Authentication failed for 'https://roberthchan:p0ntiac%2F@github.com/roberthchan/wave-runner.git/'
    at Object.exports.toError (file:///home/roberth/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/roberth/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by nmorenor** [comment]
Were taking a look at this one, at first I thought it was because @roberthchan password contains a '/' at the end (I take that from previous message). But it is using a two factor authentication (https://github.com/blog/1614-two-factor-authentication).

One way to solve this could be:

**How does it work for command-line Git?**

If you are using SSH for Git authentication, rest easy: you don't need to do anything. If you are using HTTPS Git, instead of entering your password, enter a personal access token. These can be created by going to your application settings page.

So instead of use the password in the commit dialog you could use the access-token, that sounds interesting.

Right now brackets git is using git from the command line to do git operations, after doing some extra investigation found this (https://developer.github.com/v3/auth/#working-with-two-factor-authentication) It seems that Brackets-git must be able to perform two requests and look on the response headers for a "X-GitHub-OTP: required; :2fa-type" and then do another request with the provided token via SMS. I'am new to Github so do not know what is the best we can do.

**Comment by roberthchan** [comment]
Well, It may be my mistake, use SSH for Git, It may be the best solution, thank you!
